version: "3"
services:
  inv_sig_helper:
    build: .
    command: ["--tcp", "127.0.0.1:12999"]
    ports:
      - 127.0.0.1:12999:12999
    environment:
      - RUST_LOG=info
    restart: unless-stopped
