version: "3"
services:
  inv_sig_helper:
    build:
      context: .
      dockerfile: Dockerfile
    # image: quay.io/invidious/inv-sig-helper:latest
    command: ["--tcp", "127.0.0.1:12999"]
    ports:
      - 127.0.0.1:12999:12999
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    user: 10001:10001
    security_opt:
      - no-new-privileges:true
